### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by DavidLoftus**
PR adds GoogleTest to cmake project along with a basic test. Should make it easier to accept future pull requests by assuring that existing behaviour isn't broken. Additionally provides sample code for library users.

### CODE REVIEW

**Comment by DavidLoftus** [comment]
Build fails when adding sample code to tests, any clue why?

**Comment by onqtam** [comment]
surely there are other C++ frameworks which are much easier to setup and work with than google test...? *cough* [doctest](https://github.com/onqtam/doctest) *cough* :)

**Comment by DavidLoftus** [comment]
Nice plug, although this build fail doesn't seem to be a problem with GoogleTest, but rather the CI is building it with a pre C++11 compiler.

**Comment by amiremohamadi** [comment]
@DavidLoftus Thank you for the PR!

Refer to @onqtam's comment:

> surely there are other C++ frameworks which are much easier to setup and work with than google test...? _cough_ [doctest](https://github.com/onqtam/doctest) _cough_ :)

I prefer to use `doctest` instead of `google-test`. Also I want to keep DuckX as minimal as possible.

**Comment by DavidLoftus** [comment]
> I prefer to use `doctest` instead of `google-test`. Also I want to keep DuckX as minimal as possible.
`doctest` will require a C++11 compiler, which will cause builds to fail. If this is fine I will close this PR and make a new PR that adds doctest.

**Comment by onqtam** [comment]
GCC 6 which is the only compiler in the current travis.yml file has full support for C++11. Doctest can be compiled even with GCC 4.8 since it has enough C++11 support. There is also the [```1.2.9``` tag](https://github.com/onqtam/doctest/tree/1.2.9) which is for C++98.

**Comment by DavidLoftus** [comment]
Thats what I thought but build was failing due to use of the auto keyword. I'll make the PR and we can see if it does build.

**Pull request closed without merging**
