### PR TITLE
Add run formatting support

### PR DESCRIPTION
**Pull request by AleksanderVatov**
I have implemented support for adding runs with formatting (bold, italic, underline, superscript, subscript, small caps, and shadow are supported).

### CODE REVIEW

**Comment by amiremohamadi** [comment]
@AleksanderVatov thanks for the PR! :smiley: 
It seems good to me but there's a few things:

1. we prefer to name variables and method parameters **snake_case**
2. it would be great to create a new **.cpp** file in **samples/** directory and write an example of how to use **run-formatting**

**Comment by AleksanderVatov** [comment]
Will do. Can I combine this with the issue I wrote about, with the leading and trailing spaces in runs?

**Comment by AleksanderVatov** [comment]
I overloaded the &, |, &=, and |= operators; now FormattingFlags can be used instead of int, and thus the parameter's name is no longer necessary in the header. I also added a sample.

**Comment by AleksanderVatov** [comment]
I have new changes in another branch (see https://github.com/amiremohamadi/DuckX/issues/50); I'll make a new pull request when you accept this one.

**Comment by amiremohamadi** [comment]
> Can I combine this with the issue I wrote about, with the leading and trailing spaces in runs?

It's better to open separate pull-requests but I'll merge this pull-request soon
Thanks a lot for your efforts :-)

**Pull request merged**
