### PR TITLE
Edit word

### PR DESCRIPTION
**Pull request by xsl1121**
Edit word <br/>
Dependency [libzip ](https://libzip.org/)

### CODE REVIEW

**Comment by amiremohamadi** [comment]
Hi @xsl1121 
First off, thanks for taking the time to contribute! :smiley: 

In order to avoid wasting your time, I highly encourage opening an issue to discuss whether the PR you're thinking about making will be acceptable.
Also, please read [CONTRIBUTIN.md](https://github.com/amiremohamadi/DuckX/blob/master/CONTRIBUTING.md).

**Comment by xsl1121** [comment]
ok.

**Comment by xsl1121** [comment]
Thanks , When I tried to modify the Word document, I finally got a corrupted file. I looked at the generated file and found that there are two word/document.xml

Archive:  my_test.docx
  Length      Date    Time    Name
---------  ---------- -----   ----
      573  02-03-2019 17:16   _rels/.rels
      513  02-03-2019 17:16   docProps/app.xml
      732  02-03-2019 17:16   docProps/core.xml
      531  02-03-2019 17:16   word/_rels/document.xml.rels
      280  02-03-2019 17:16   word/settings.xml
      853  02-03-2019 17:16   word/fontTable.xml
     1480  02-03-2019 17:16   word/document.xml
     2585  02-03-2019 17:16   word/styles.xml
     1118  02-03-2019 17:16   [Content_Types].xml
     1602  07-03-2019 23:14   word/document.xml
---------                     -------
    10267                     10 files

**Comment by amiremohamadi** [comment]
Again thanks @xsl1121.
I think this happened because of `Zip` library that I used.
I'll be happy if you help me to solve this problem :)

**Pull request closed without merging**
